#!/usr/bin/env python3
"""
Rename files generated by hacha; find/replace all links and references.
(e.g., thinkjava2_002.html -> chapter-01.html)
"""

import os
import sys


def oldname(i):
    return "thinkjava2_{:03}.html".format(i + 1)


def newname(i):
    if i == 0:
        return "preface.html"
    elif i == 22:
        return "book-index.html"
    elif i < 18:
        return "chapter-{:02}.html".format(i)
    else:
        return "appendix-" + chr(79 + i) + ".html"


def main():

    # build replacement dict
    names = {oldname(i): newname(i) for i in range(23)}
    names["index.html"] = "index.html"

    # for each html file
    for old, new in names.items():

        # rename the file
        os.rename(old, new)

        # replace all links
        with open(new, "r") as nf:
            html = nf.read()
        for old2, new2 in names.items():
            html = html.replace(old2, new2)
        with open(new, "w") as nf:
            nf.write(html)


if __name__ == "__main__":
    if len(sys.argv) == 2:
        os.chdir(sys.argv[1])
        main()
    else:
        print("Usage: python3", sys.argv[0], "htmldir")
